/*----------------------------------------------------------------------
 * This file is generated by mk_parser_show.py.
 *----------------------------------------------------------------------*/
#ifndef __CPARSER_SHOW_TREE_H__
#define __CPARSER_SHOW_TREE_H__

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

extern cparser_node_t cparser_show_root;

cparser_result_t cparser_cmd_show_tamper_tampername(cparser_context_t *context,
    char **tampername_ptr);
cparser_result_t cparser_cmd_show_tamper_disk(cparser_context_t *context);
cparser_result_t cparser_cmd_show_tamper_log_all(cparser_context_t *context);
cparser_result_t cparser_cmd_show_tamper_log_all_recent_hours(cparser_context_t *context,
    uint32_t *hours_ptr);
cparser_result_t cparser_cmd_show_tamper_log_all_start_time_start_year_start_month_start_day_start_hour_start_min_start_sec_end_time_end_year_end_month_end_day_end_hour_end_min_end_sec(cparser_context_t *context,
    uint32_t *start_year_ptr,
    uint32_t *start_month_ptr,
    uint32_t *start_day_ptr,
    uint32_t *start_hour_ptr,
    uint32_t *start_min_ptr,
    uint32_t *start_sec_ptr,
    uint32_t *end_year_ptr,
    uint32_t *end_month_ptr,
    uint32_t *end_day_ptr,
    uint32_t *end_hour_ptr,
    uint32_t *end_min_ptr,
    uint32_t *end_sec_ptr);
cparser_result_t cparser_cmd_show_tamper_log_tamper_name(cparser_context_t *context,
    char **name_ptr);
cparser_result_t cparser_cmd_show_tamper_log_tamper_name_recent_hours(cparser_context_t *context,
    char **name_ptr,
    uint32_t *hours_ptr);
cparser_result_t cparser_cmd_show_tamper_log_tamper_name_start_time_start_year_start_month_start_day_start_hour_start_min_start_sec_end_time_end_year_end_month_end_day_end_hour_end_min_end_sec(cparser_context_t *context,
    char **name_ptr,
    uint32_t *start_year_ptr,
    uint32_t *start_month_ptr,
    uint32_t *start_day_ptr,
    uint32_t *start_hour_ptr,
    uint32_t *start_min_ptr,
    uint32_t *start_sec_ptr,
    uint32_t *end_year_ptr,
    uint32_t *end_month_ptr,
    uint32_t *end_day_ptr,
    uint32_t *end_hour_ptr,
    uint32_t *end_min_ptr,
    uint32_t *end_sec_ptr);
cparser_result_t cparser_cmd_show_admin_log(cparser_context_t *context);
cparser_result_t cparser_cmd_show_admin_log_recent_hours(cparser_context_t *context,
    uint32_t *hours_ptr);
cparser_result_t cparser_cmd_show_admin_log_start_time_start_year_start_month_start_day_start_hour_start_min_start_sec_end_time_end_year_end_month_end_day_end_hour_end_min_end_sec(cparser_context_t *context,
    uint32_t *start_year_ptr,
    uint32_t *start_month_ptr,
    uint32_t *start_day_ptr,
    uint32_t *start_hour_ptr,
    uint32_t *start_min_ptr,
    uint32_t *start_sec_ptr,
    uint32_t *end_year_ptr,
    uint32_t *end_month_ptr,
    uint32_t *end_day_ptr,
    uint32_t *end_hour_ptr,
    uint32_t *end_min_ptr,
    uint32_t *end_sec_ptr);
cparser_result_t cparser_cmd_show_running_config(cparser_context_t *context);

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* __CPARSER_SHOW_TREE_H__ */
