/*----------------------------------------------------------------------
 * This file is generated by mk_parser.py.
 *----------------------------------------------------------------------*/
#include <assert.h>
#include <stdint.h>
#include <stdio.h>
#include "cparser.h"
#include "cparser_priv.h"
#include "cparser_token.h"
#include "cparser_tree.h"

cparser_result_t
cparser_glue_enable (cparser_t *parser)
{
    if (parser->mode == CPARSER_MODE_CONFIG) {;
    };
    cparser_cmd_enable(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_st_write (cparser_t *parser)
{
    if (parser->mode == CPARSER_MODE_CONFIG) {;
    };
    cparser_cmd_st_write(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_st_load (cparser_t *parser)
{
    if (parser->mode == CPARSER_MODE_CONFIG) {;
    };
    cparser_cmd_st_load(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_st_configure (cparser_t *parser)
{
    if (parser->mode == CPARSER_MODE_CONFIG) {;
    };
    cparser_cmd_st_configure(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_monther_no_tamper_name (cparser_t *parser)
{
    char *name_val;
    char **name_ptr = NULL;
    cparser_result_t rc;

    if (parser->mode == CPARSER_MODE_CONFIG) {;
       rc = cparser_get_string(&parser->tokens[2], &name_val);
        if (CPARSER_OK != rc) {
            cparser_printf(&parser->context, "Invalid value!\n");
            return CPARSER_OK;
        }
        name_ptr = &name_val;
    };
    cparser_cmd_monther_no_tamper_name(&parser->context,
        name_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_monther_tamper_name (cparser_t *parser)
{
    char *name_val;
    char **name_ptr = NULL;
    cparser_result_t rc;

    if (parser->mode == CPARSER_MODE_CONFIG) {;
       rc = cparser_get_string(&parser->tokens[1], &name_val);
        if (CPARSER_OK != rc) {
            cparser_printf(&parser->context, "Invalid value!\n");
            return CPARSER_OK;
        }
        name_ptr = &name_val;
    };
    cparser_cmd_monther_tamper_name(&parser->context,
        name_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_son_description_content (cparser_t *parser)
{
    char *content_val;
    char **content_ptr = NULL;
    cparser_result_t rc;

    if (parser->mode == CPARSER_MODE_CONFIG) {;
       rc = cparser_get_string(&parser->tokens[1], &content_val);
        if (CPARSER_OK != rc) {
            cparser_printf(&parser->context, "Invalid value!\n");
            return CPARSER_OK;
        }
        content_ptr = &content_val;
    };
    cparser_cmd_son_description_content(&parser->context,
        content_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_son_no_description (cparser_t *parser)
{
    if (parser->mode == CPARSER_MODE_CONFIG) {;
    };
    cparser_cmd_son_no_description(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_son_no_email (cparser_t *parser)
{
    if (parser->mode == CPARSER_MODE_CONFIG) {;
    };
    cparser_cmd_son_no_email(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_son_no_connect (cparser_t *parser)
{
    if (parser->mode == CPARSER_MODE_CONFIG) {;
    };
    cparser_cmd_son_no_connect(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_son_no_document_root (cparser_t *parser)
{
    if (parser->mode == CPARSER_MODE_CONFIG) {;
    };
    cparser_cmd_son_no_document_root(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_son_no_monitor_folder_depth (cparser_t *parser)
{
    if (parser->mode == CPARSER_MODE_CONFIG) {;
    };
    cparser_cmd_son_no_monitor_folder_depth(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_son_no_monitor_folder_root_folder (cparser_t *parser)
{
    if (parser->mode == CPARSER_MODE_CONFIG) {;
    };
    cparser_cmd_son_no_monitor_folder_root_folder(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_son_no_monitor_folder_other_folder (cparser_t *parser)
{
    if (parser->mode == CPARSER_MODE_CONFIG) {;
    };
    cparser_cmd_son_no_monitor_folder_other_folder(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_son_no_monitor_file_size (cparser_t *parser)
{
    if (parser->mode == CPARSER_MODE_CONFIG) {;
    };
    cparser_cmd_son_no_monitor_file_size(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_son_no_monitor_file_type_exclude_extension (cparser_t *parser)
{
    char *extension_val;
    char **extension_ptr = NULL;
    cparser_result_t rc;

    if (parser->mode == CPARSER_MODE_CONFIG) {;
       rc = cparser_get_string(&parser->tokens[3], &extension_val);
        if (CPARSER_OK != rc) {
            cparser_printf(&parser->context, "Invalid value!\n");
            return CPARSER_OK;
        }
        extension_ptr = &extension_val;
    };
    cparser_cmd_son_no_monitor_file_type_exclude_extension(&parser->context,
        extension_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_son_no_restore_mode (cparser_t *parser)
{
    if (parser->mode == CPARSER_MODE_CONFIG) {;
    };
    cparser_cmd_son_no_restore_mode(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_son_no_monitor (cparser_t *parser)
{
    if (parser->mode == CPARSER_MODE_CONFIG) {;
    };
    cparser_cmd_son_no_monitor(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_son_no_disk_size (cparser_t *parser)
{
    if (parser->mode == CPARSER_MODE_CONFIG) {;
    };
    cparser_cmd_son_no_disk_size(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_son_email_address (cparser_t *parser)
{
    char *address_val;
    char **address_ptr = NULL;
    cparser_result_t rc;

    if (parser->mode == CPARSER_MODE_CONFIG) {;
       rc = cparser_get_string(&parser->tokens[1], &address_val);
        if (CPARSER_OK != rc) {
            cparser_printf(&parser->context, "Invalid value!\n");
            return CPARSER_OK;
        }
        address_ptr = &address_val;
    };
    cparser_cmd_son_email_address(&parser->context,
        address_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_son_connect_protocol_protocol_object_var_port_number_username_name_password_cipher_text_pw (cparser_t *parser)
{
    char *protocol_val;
    char **protocol_ptr = NULL;
    char *object_val;
    char **object_ptr = NULL;
    char *var_val;
    char **var_ptr = NULL;
    uint32_t number_val;
    uint32_t *number_ptr = NULL;
    char *name_val;
    char **name_ptr = NULL;
    char *pw_val;
    char **pw_ptr = NULL;
    cparser_result_t rc;

    if (parser->mode == CPARSER_MODE_CONFIG) {;
       rc = cparser_get_list(&parser->tokens[2], &protocol_val);
        if (CPARSER_OK != rc) {
            cparser_printf(&parser->context, "Invalid value!\n");
            return CPARSER_OK;
        }
        protocol_ptr = &protocol_val;
       rc = cparser_get_list(&parser->tokens[3], &object_val);
        if (CPARSER_OK != rc) {
            cparser_printf(&parser->context, "Invalid value!\n");
            return CPARSER_OK;
        }
        object_ptr = &object_val;
       rc = cparser_get_string(&parser->tokens[4], &var_val);
        if (CPARSER_OK != rc) {
            cparser_printf(&parser->context, "Invalid value!\n");
            return CPARSER_OK;
        }
        var_ptr = &var_val;
       rc = cparser_get_uint(&parser->tokens[6], &number_val);
        if (CPARSER_OK != rc) {
            cparser_printf(&parser->context, "Invalid value!\n");
            return CPARSER_OK;
        }
        number_ptr = &number_val;
       rc = cparser_get_string(&parser->tokens[8], &name_val);
        if (CPARSER_OK != rc) {
            cparser_printf(&parser->context, "Invalid value!\n");
            return CPARSER_OK;
        }
        name_ptr = &name_val;
       rc = cparser_get_string(&parser->tokens[11], &pw_val);
        if (CPARSER_OK != rc) {
            cparser_printf(&parser->context, "Invalid value!\n");
            return CPARSER_OK;
        }
        pw_ptr = &pw_val;
    };
    cparser_cmd_son_connect_protocol_protocol_object_var_port_number_username_name_password_cipher_text_pw(&parser->context,
        protocol_ptr,
        object_ptr,
        var_ptr,
        number_ptr,
        name_ptr,
        pw_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_son_connect_protocol_protocol_object_var_port_number_username_name_password_pw (cparser_t *parser)
{
    char *protocol_val;
    char **protocol_ptr = NULL;
    char *object_val;
    char **object_ptr = NULL;
    char *var_val;
    char **var_ptr = NULL;
    uint32_t number_val;
    uint32_t *number_ptr = NULL;
    char *name_val;
    char **name_ptr = NULL;
    char *pw_val;
    char **pw_ptr = NULL;
    cparser_result_t rc;

    if (parser->mode == CPARSER_MODE_CONFIG) {;
       rc = cparser_get_list(&parser->tokens[2], &protocol_val);
        if (CPARSER_OK != rc) {
            cparser_printf(&parser->context, "Invalid value!\n");
            return CPARSER_OK;
        }
        protocol_ptr = &protocol_val;
       rc = cparser_get_list(&parser->tokens[3], &object_val);
        if (CPARSER_OK != rc) {
            cparser_printf(&parser->context, "Invalid value!\n");
            return CPARSER_OK;
        }
        object_ptr = &object_val;
       rc = cparser_get_string(&parser->tokens[4], &var_val);
        if (CPARSER_OK != rc) {
            cparser_printf(&parser->context, "Invalid value!\n");
            return CPARSER_OK;
        }
        var_ptr = &var_val;
       rc = cparser_get_uint(&parser->tokens[6], &number_val);
        if (CPARSER_OK != rc) {
            cparser_printf(&parser->context, "Invalid value!\n");
            return CPARSER_OK;
        }
        number_ptr = &number_val;
       rc = cparser_get_string(&parser->tokens[8], &name_val);
        if (CPARSER_OK != rc) {
            cparser_printf(&parser->context, "Invalid value!\n");
            return CPARSER_OK;
        }
        name_ptr = &name_val;
       rc = cparser_get_string(&parser->tokens[10], &pw_val);
        if (CPARSER_OK != rc) {
            cparser_printf(&parser->context, "Invalid value!\n");
            return CPARSER_OK;
        }
        pw_ptr = &pw_val;
    };
    cparser_cmd_son_connect_protocol_protocol_object_var_port_number_username_name_password_pw(&parser->context,
        protocol_ptr,
        object_ptr,
        var_ptr,
        number_ptr,
        name_ptr,
        pw_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_son_document_root_path (cparser_t *parser)
{
    char *path_val;
    char **path_ptr = NULL;
    cparser_result_t rc;

    if (parser->mode == CPARSER_MODE_CONFIG) {;
       rc = cparser_get_string(&parser->tokens[1], &path_val);
        if (CPARSER_OK != rc) {
            cparser_printf(&parser->context, "Invalid value!\n");
            return CPARSER_OK;
        }
        path_ptr = &path_val;
    };
    cparser_cmd_son_document_root_path(&parser->context,
        path_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_son_monitor_folder_depth_level (cparser_t *parser)
{
    int32_t level_val;
    int32_t *level_ptr = NULL;
    cparser_result_t rc;

    if (parser->mode == CPARSER_MODE_CONFIG) {;
       rc = cparser_get_int(&parser->tokens[2], &level_val);
        if (CPARSER_OK != rc) {
            cparser_printf(&parser->context, "Invalid value!\n");
            return CPARSER_OK;
        }
        level_ptr = &level_val;
    };
    cparser_cmd_son_monitor_folder_depth_level(&parser->context,
        level_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_son_monitor_folder_root_folder_seconds (cparser_t *parser)
{
    int32_t seconds_val;
    int32_t *seconds_ptr = NULL;
    cparser_result_t rc;

    if (parser->mode == CPARSER_MODE_CONFIG) {;
       rc = cparser_get_int(&parser->tokens[2], &seconds_val);
        if (CPARSER_OK != rc) {
            cparser_printf(&parser->context, "Invalid value!\n");
            return CPARSER_OK;
        }
        seconds_ptr = &seconds_val;
    };
    cparser_cmd_son_monitor_folder_root_folder_seconds(&parser->context,
        seconds_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_son_monitor_folder_other_folder_seconds (cparser_t *parser)
{
    int32_t seconds_val;
    int32_t *seconds_ptr = NULL;
    cparser_result_t rc;

    if (parser->mode == CPARSER_MODE_CONFIG) {;
       rc = cparser_get_int(&parser->tokens[2], &seconds_val);
        if (CPARSER_OK != rc) {
            cparser_printf(&parser->context, "Invalid value!\n");
            return CPARSER_OK;
        }
        seconds_ptr = &seconds_val;
    };
    cparser_cmd_son_monitor_folder_other_folder_seconds(&parser->context,
        seconds_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_son_monitor_file_size_number (cparser_t *parser)
{
    uint32_t number_val;
    uint32_t *number_ptr = NULL;
    cparser_result_t rc;

    if (parser->mode == CPARSER_MODE_CONFIG) {;
       rc = cparser_get_uint(&parser->tokens[1], &number_val);
        if (CPARSER_OK != rc) {
            cparser_printf(&parser->context, "Invalid value!\n");
            return CPARSER_OK;
        }
        number_ptr = &number_val;
    };
    cparser_cmd_son_monitor_file_size_number(&parser->context,
        number_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_son_monitor_file_type_exclude_extension (cparser_t *parser)
{
    char *extension_val;
    char **extension_ptr = NULL;
    cparser_result_t rc;

    if (parser->mode == CPARSER_MODE_CONFIG) {;
       rc = cparser_get_string(&parser->tokens[2], &extension_val);
        if (CPARSER_OK != rc) {
            cparser_printf(&parser->context, "Invalid value!\n");
            return CPARSER_OK;
        }
        extension_ptr = &extension_val;
    };
    cparser_cmd_son_monitor_file_type_exclude_extension(&parser->context,
        extension_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_son_restore_mode_option (cparser_t *parser)
{
    char *option_val;
    char **option_ptr = NULL;
    cparser_result_t rc;

    if (parser->mode == CPARSER_MODE_CONFIG) {;
       rc = cparser_get_list(&parser->tokens[1], &option_val);
        if (CPARSER_OK != rc) {
            cparser_printf(&parser->context, "Invalid value!\n");
            return CPARSER_OK;
        }
        option_ptr = &option_val;
    };
    cparser_cmd_son_restore_mode_option(&parser->context,
        option_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_son_monitor_option (cparser_t *parser)
{
    char *option_val;
    char **option_ptr = NULL;
    cparser_result_t rc;

    if (parser->mode == CPARSER_MODE_CONFIG) {;
       rc = cparser_get_list(&parser->tokens[1], &option_val);
        if (CPARSER_OK != rc) {
            cparser_printf(&parser->context, "Invalid value!\n");
            return CPARSER_OK;
        }
        option_ptr = &option_val;
    };
    cparser_cmd_son_monitor_option(&parser->context,
        option_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_son_disk_size_size (cparser_t *parser)
{
    int32_t size_val;
    int32_t *size_ptr = NULL;
    cparser_result_t rc;

    if (parser->mode == CPARSER_MODE_CONFIG) {;
       rc = cparser_get_int(&parser->tokens[1], &size_val);
        if (CPARSER_OK != rc) {
            cparser_printf(&parser->context, "Invalid value!\n");
            return CPARSER_OK;
        }
        size_ptr = &size_val;
    };
    cparser_cmd_son_disk_size_size(&parser->context,
        size_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_son_restore_tamper_all (cparser_t *parser)
{
    if (parser->mode == CPARSER_MODE_CONFIG) {;
    };
    cparser_cmd_son_restore_tamper_all(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_son_restore_tamper_file_name (cparser_t *parser)
{
    char *name_val;
    char **name_ptr = NULL;
    cparser_result_t rc;

    if (parser->mode == CPARSER_MODE_CONFIG) {;
       rc = cparser_get_string(&parser->tokens[2], &name_val);
        if (CPARSER_OK != rc) {
            cparser_printf(&parser->context, "Invalid value!\n");
            return CPARSER_OK;
        }
        name_ptr = &name_val;
    };
    cparser_cmd_son_restore_tamper_file_name(&parser->context,
        name_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_son_view_file_content_name (cparser_t *parser)
{
    char *name_val;
    char **name_ptr = NULL;
    cparser_result_t rc;

    if (parser->mode == CPARSER_MODE_CONFIG) {;
       rc = cparser_get_string(&parser->tokens[2], &name_val);
        if (CPARSER_OK != rc) {
            cparser_printf(&parser->context, "Invalid value!\n");
            return CPARSER_OK;
        }
        name_ptr = &name_val;
    };
    cparser_cmd_son_view_file_content_name(&parser->context,
        name_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_son_view_tamper_content_name (cparser_t *parser)
{
    char *name_val;
    char **name_ptr = NULL;
    cparser_result_t rc;

    if (parser->mode == CPARSER_MODE_CONFIG) {;
       rc = cparser_get_string(&parser->tokens[2], &name_val);
        if (CPARSER_OK != rc) {
            cparser_printf(&parser->context, "Invalid value!\n");
            return CPARSER_OK;
        }
        name_ptr = &name_val;
    };
    cparser_cmd_son_view_tamper_content_name(&parser->context,
        name_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_son_view_tamper_filename (cparser_t *parser)
{
    if (parser->mode == CPARSER_MODE_CONFIG) {;
    };
    cparser_cmd_son_view_tamper_filename(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_son_clear_tamper_all (cparser_t *parser)
{
    if (parser->mode == CPARSER_MODE_CONFIG) {;
    };
    cparser_cmd_son_clear_tamper_all(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_son_clear_tamper_file_name (cparser_t *parser)
{
    char *name_val;
    char **name_ptr = NULL;
    cparser_result_t rc;

    if (parser->mode == CPARSER_MODE_CONFIG) {;
       rc = cparser_get_string(&parser->tokens[2], &name_val);
        if (CPARSER_OK != rc) {
            cparser_printf(&parser->context, "Invalid value!\n");
            return CPARSER_OK;
        }
        name_ptr = &name_val;
    };
    cparser_cmd_son_clear_tamper_file_name(&parser->context,
        name_ptr);
    return CPARSER_OK;
}

cparser_node_t cparser_node_monther_tamper_name_root_clear_tamper_file_name_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_son_clear_tamper_file_name,
    "delete the file tampered with filename",
    NULL,
    NULL
};

cparser_node_t cparser_node_monther_tamper_name_root_clear_tamper_file_name = {
    CPARSER_NODE_STRING,
    0,
    "<STRING:name>",
    NULL,
    NULL,
    &cparser_node_monther_tamper_name_root_clear_tamper_file_name_eol
};

cparser_node_t cparser_node_monther_tamper_name_root_clear_tamper_file = {
    CPARSER_NODE_KEYWORD,
    0,
    "file",
    NULL,
    NULL,
    &cparser_node_monther_tamper_name_root_clear_tamper_file_name
};

cparser_node_t cparser_node_monther_tamper_name_root_clear_tamper_all_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_son_clear_tamper_all,
    "delete all the file tampered",
    NULL,
    NULL
};

cparser_node_t cparser_node_monther_tamper_name_root_clear_tamper_all = {
    CPARSER_NODE_KEYWORD,
    0,
    "all",
    NULL,
    &cparser_node_monther_tamper_name_root_clear_tamper_file,
    &cparser_node_monther_tamper_name_root_clear_tamper_all_eol
};

cparser_node_t cparser_node_monther_tamper_name_root_clear_tamper = {
    CPARSER_NODE_KEYWORD,
    0,
    "clear-tamper",
    NULL,
    NULL,
    &cparser_node_monther_tamper_name_root_clear_tamper_all
};

cparser_node_t cparser_node_monther_tamper_name_root_view_tamper_filename_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_son_view_tamper_filename,
    "view the tampered filename",
    NULL,
    NULL
};

cparser_node_t cparser_node_monther_tamper_name_root_view_tamper_filename = {
    CPARSER_NODE_KEYWORD,
    0,
    "tamper-filename",
    NULL,
    NULL,
    &cparser_node_monther_tamper_name_root_view_tamper_filename_eol
};

cparser_node_t cparser_node_monther_tamper_name_root_view_tamper_content_name_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_son_view_tamper_content_name,
    "view the tampered content with filename",
    NULL,
    NULL
};

cparser_node_t cparser_node_monther_tamper_name_root_view_tamper_content_name = {
    CPARSER_NODE_STRING,
    0,
    "<STRING:name>",
    NULL,
    NULL,
    &cparser_node_monther_tamper_name_root_view_tamper_content_name_eol
};

cparser_node_t cparser_node_monther_tamper_name_root_view_tamper_content = {
    CPARSER_NODE_KEYWORD,
    0,
    "tamper-content",
    NULL,
    &cparser_node_monther_tamper_name_root_view_tamper_filename,
    &cparser_node_monther_tamper_name_root_view_tamper_content_name
};

cparser_node_t cparser_node_monther_tamper_name_root_view_file_content_name_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_son_view_file_content_name,
    "view the tampered file content with filename",
    NULL,
    NULL
};

cparser_node_t cparser_node_monther_tamper_name_root_view_file_content_name = {
    CPARSER_NODE_STRING,
    0,
    "<STRING:name>",
    NULL,
    NULL,
    &cparser_node_monther_tamper_name_root_view_file_content_name_eol
};

cparser_node_t cparser_node_monther_tamper_name_root_view_file_content = {
    CPARSER_NODE_KEYWORD,
    0,
    "file-content",
    NULL,
    &cparser_node_monther_tamper_name_root_view_tamper_content,
    &cparser_node_monther_tamper_name_root_view_file_content_name
};

cparser_node_t cparser_node_monther_tamper_name_root_view = {
    CPARSER_NODE_KEYWORD,
    0,
    "view",
    NULL,
    &cparser_node_monther_tamper_name_root_clear_tamper,
    &cparser_node_monther_tamper_name_root_view_file_content
};

cparser_node_t cparser_node_monther_tamper_name_root_restore_tamper_file_name_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_son_restore_tamper_file_name,
    "restore file with name",
    NULL,
    NULL
};

cparser_node_t cparser_node_monther_tamper_name_root_restore_tamper_file_name = {
    CPARSER_NODE_STRING,
    0,
    "<STRING:name>",
    NULL,
    NULL,
    &cparser_node_monther_tamper_name_root_restore_tamper_file_name_eol
};

cparser_node_t cparser_node_monther_tamper_name_root_restore_tamper_file = {
    CPARSER_NODE_KEYWORD,
    0,
    "file",
    NULL,
    NULL,
    &cparser_node_monther_tamper_name_root_restore_tamper_file_name
};

cparser_node_t cparser_node_monther_tamper_name_root_restore_tamper_all_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_son_restore_tamper_all,
    "restore all tampered file",
    NULL,
    NULL
};

cparser_node_t cparser_node_monther_tamper_name_root_restore_tamper_all = {
    CPARSER_NODE_KEYWORD,
    0,
    "all",
    NULL,
    &cparser_node_monther_tamper_name_root_restore_tamper_file,
    &cparser_node_monther_tamper_name_root_restore_tamper_all_eol
};

cparser_node_t cparser_node_monther_tamper_name_root_restore_tamper = {
    CPARSER_NODE_KEYWORD,
    0,
    "restore-tamper",
    NULL,
    &cparser_node_monther_tamper_name_root_view,
    &cparser_node_monther_tamper_name_root_restore_tamper_all
};

cparser_node_t cparser_node_monther_tamper_name_root_disk_size_size_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_son_disk_size_size,
    "set the disk with size (M)",
    NULL,
    NULL
};

cparser_node_t cparser_node_monther_tamper_name_root_disk_size_size = {
    CPARSER_NODE_INT,
    0,
    "<INT:size>",
    NULL,
    NULL,
    &cparser_node_monther_tamper_name_root_disk_size_size_eol
};

cparser_node_t cparser_node_monther_tamper_name_root_disk_size = {
    CPARSER_NODE_KEYWORD,
    0,
    "disk-size",
    NULL,
    &cparser_node_monther_tamper_name_root_restore_tamper,
    &cparser_node_monther_tamper_name_root_disk_size_size
};

cparser_node_t cparser_node_monther_tamper_name_root_monitor_option_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_son_monitor_option,
    "enable monitor",
    NULL,
    NULL
};

cparser_list_node_t cparser_list_node_monther_tamper_name_root_monitor_option_disable = {
    NULL,
    "disable"
 };

cparser_list_node_t cparser_list_node_monther_tamper_name_root_monitor_option_enable = {
    &cparser_list_node_monther_tamper_name_root_monitor_option_disable,
    "enable"
 };

cparser_node_t cparser_node_monther_tamper_name_root_monitor_option = {
    CPARSER_NODE_LIST,
    0,
    &cparser_list_node_monther_tamper_name_root_monitor_option_enable,
    NULL,
    NULL,
    &cparser_node_monther_tamper_name_root_monitor_option_eol
};

cparser_node_t cparser_node_monther_tamper_name_root_monitor = {
    CPARSER_NODE_KEYWORD,
    0,
    "monitor",
    NULL,
    &cparser_node_monther_tamper_name_root_disk_size,
    &cparser_node_monther_tamper_name_root_monitor_option
};

cparser_node_t cparser_node_monther_tamper_name_root_restore_mode_option_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_son_restore_mode_option,
    "config auto restore",
    NULL,
    NULL
};

cparser_list_node_t cparser_list_node_monther_tamper_name_root_restore_mode_option_manual = {
    NULL,
    "manual"
 };

cparser_list_node_t cparser_list_node_monther_tamper_name_root_restore_mode_option_auto = {
    &cparser_list_node_monther_tamper_name_root_restore_mode_option_manual,
    "auto"
 };

cparser_node_t cparser_node_monther_tamper_name_root_restore_mode_option = {
    CPARSER_NODE_LIST,
    0,
    &cparser_list_node_monther_tamper_name_root_restore_mode_option_auto,
    NULL,
    NULL,
    &cparser_node_monther_tamper_name_root_restore_mode_option_eol
};

cparser_node_t cparser_node_monther_tamper_name_root_restore_mode = {
    CPARSER_NODE_KEYWORD,
    0,
    "restore-mode",
    NULL,
    &cparser_node_monther_tamper_name_root_monitor,
    &cparser_node_monther_tamper_name_root_restore_mode_option
};

cparser_node_t cparser_node_monther_tamper_name_root_monitor_file_type_exclude_extension_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_son_monitor_file_type_exclude_extension,
    "config monitor file type",
    NULL,
    NULL
};

cparser_node_t cparser_node_monther_tamper_name_root_monitor_file_type_exclude_extension = {
    CPARSER_NODE_STRING,
    0,
    "<STRING:extension>",
    NULL,
    NULL,
    &cparser_node_monther_tamper_name_root_monitor_file_type_exclude_extension_eol
};

cparser_node_t cparser_node_monther_tamper_name_root_monitor_file_type_exclude = {
    CPARSER_NODE_KEYWORD,
    0,
    "exclude",
    NULL,
    NULL,
    &cparser_node_monther_tamper_name_root_monitor_file_type_exclude_extension
};

cparser_node_t cparser_node_monther_tamper_name_root_monitor_file_type = {
    CPARSER_NODE_KEYWORD,
    0,
    "monitor-file-type",
    NULL,
    &cparser_node_monther_tamper_name_root_restore_mode,
    &cparser_node_monther_tamper_name_root_monitor_file_type_exclude
};

cparser_node_t cparser_node_monther_tamper_name_root_monitor_file_size_number_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_son_monitor_file_size_number,
    "config monitor file size",
    NULL,
    NULL
};

cparser_node_t cparser_node_monther_tamper_name_root_monitor_file_size_number = {
    CPARSER_NODE_UINT,
    0,
    "<UINT:number>",
    NULL,
    NULL,
    &cparser_node_monther_tamper_name_root_monitor_file_size_number_eol
};

cparser_node_t cparser_node_monther_tamper_name_root_monitor_file_size = {
    CPARSER_NODE_KEYWORD,
    0,
    "monitor-file-size",
    NULL,
    &cparser_node_monther_tamper_name_root_monitor_file_type,
    &cparser_node_monther_tamper_name_root_monitor_file_size_number
};

cparser_node_t cparser_node_monther_tamper_name_root_monitor_folder_other_folder_seconds_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_son_monitor_folder_other_folder_seconds,
    "config monitor folder with other-folder",
    NULL,
    NULL
};

cparser_node_t cparser_node_monther_tamper_name_root_monitor_folder_other_folder_seconds = {
    CPARSER_NODE_INT,
    0,
    "<INT:seconds>",
    NULL,
    NULL,
    &cparser_node_monther_tamper_name_root_monitor_folder_other_folder_seconds_eol
};

cparser_node_t cparser_node_monther_tamper_name_root_monitor_folder_other_folder = {
    CPARSER_NODE_KEYWORD,
    0,
    "other-folder",
    NULL,
    NULL,
    &cparser_node_monther_tamper_name_root_monitor_folder_other_folder_seconds
};

cparser_node_t cparser_node_monther_tamper_name_root_monitor_folder_root_folder_seconds_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_son_monitor_folder_root_folder_seconds,
    "config monitor folder with root-folder",
    NULL,
    NULL
};

cparser_node_t cparser_node_monther_tamper_name_root_monitor_folder_root_folder_seconds = {
    CPARSER_NODE_INT,
    0,
    "<INT:seconds>",
    NULL,
    NULL,
    &cparser_node_monther_tamper_name_root_monitor_folder_root_folder_seconds_eol
};

cparser_node_t cparser_node_monther_tamper_name_root_monitor_folder_root_folder = {
    CPARSER_NODE_KEYWORD,
    0,
    "root-folder",
    NULL,
    &cparser_node_monther_tamper_name_root_monitor_folder_other_folder,
    &cparser_node_monther_tamper_name_root_monitor_folder_root_folder_seconds
};

cparser_node_t cparser_node_monther_tamper_name_root_monitor_folder_depth_level_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_son_monitor_folder_depth_level,
    "config monitor folder with depth",
    NULL,
    NULL
};

cparser_node_t cparser_node_monther_tamper_name_root_monitor_folder_depth_level = {
    CPARSER_NODE_INT,
    0,
    "<INT:level>",
    NULL,
    NULL,
    &cparser_node_monther_tamper_name_root_monitor_folder_depth_level_eol
};

cparser_node_t cparser_node_monther_tamper_name_root_monitor_folder_depth = {
    CPARSER_NODE_KEYWORD,
    0,
    "depth",
    NULL,
    &cparser_node_monther_tamper_name_root_monitor_folder_root_folder,
    &cparser_node_monther_tamper_name_root_monitor_folder_depth_level
};

cparser_node_t cparser_node_monther_tamper_name_root_monitor_folder = {
    CPARSER_NODE_KEYWORD,
    0,
    "monitor-folder",
    NULL,
    &cparser_node_monther_tamper_name_root_monitor_file_size,
    &cparser_node_monther_tamper_name_root_monitor_folder_depth
};

cparser_node_t cparser_node_monther_tamper_name_root_document_root_path_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_son_document_root_path,
    "config the document root",
    NULL,
    NULL
};

cparser_node_t cparser_node_monther_tamper_name_root_document_root_path = {
    CPARSER_NODE_STRING,
    0,
    "<STRING:path>",
    NULL,
    NULL,
    &cparser_node_monther_tamper_name_root_document_root_path_eol
};

cparser_node_t cparser_node_monther_tamper_name_root_document_root = {
    CPARSER_NODE_KEYWORD,
    0,
    "document-root",
    NULL,
    &cparser_node_monther_tamper_name_root_monitor_folder,
    &cparser_node_monther_tamper_name_root_document_root_path
};

cparser_node_t cparser_node_monther_tamper_name_root_connect_protocol_protocol_object_var_port_number_username_name_password_pw_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_son_connect_protocol_protocol_object_var_port_number_username_name_password_pw,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_monther_tamper_name_root_connect_protocol_protocol_object_var_port_number_username_name_password_pw = {
    CPARSER_NODE_STRING,
    0,
    "<STRING:pw>",
    NULL,
    NULL,
    &cparser_node_monther_tamper_name_root_connect_protocol_protocol_object_var_port_number_username_name_password_pw_eol
};

cparser_node_t cparser_node_monther_tamper_name_root_connect_protocol_protocol_object_var_port_number_username_name_password_cipher_text_pw_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_son_connect_protocol_protocol_object_var_port_number_username_name_password_cipher_text_pw,
    "config connection attribution with server-ip",
    NULL,
    NULL
};

cparser_node_t cparser_node_monther_tamper_name_root_connect_protocol_protocol_object_var_port_number_username_name_password_cipher_text_pw = {
    CPARSER_NODE_STRING,
    0,
    "<STRING:pw>",
    NULL,
    NULL,
    &cparser_node_monther_tamper_name_root_connect_protocol_protocol_object_var_port_number_username_name_password_cipher_text_pw_eol
};

cparser_node_t cparser_node_monther_tamper_name_root_connect_protocol_protocol_object_var_port_number_username_name_password_cipher_text = {
    CPARSER_NODE_KEYWORD,
    0,
    "cipher-text",
    NULL,
    &cparser_node_monther_tamper_name_root_connect_protocol_protocol_object_var_port_number_username_name_password_pw,
    &cparser_node_monther_tamper_name_root_connect_protocol_protocol_object_var_port_number_username_name_password_cipher_text_pw
};

cparser_node_t cparser_node_monther_tamper_name_root_connect_protocol_protocol_object_var_port_number_username_name_password = {
    CPARSER_NODE_KEYWORD,
    0,
    "password",
    NULL,
    NULL,
    &cparser_node_monther_tamper_name_root_connect_protocol_protocol_object_var_port_number_username_name_password_cipher_text
};

cparser_node_t cparser_node_monther_tamper_name_root_connect_protocol_protocol_object_var_port_number_username_name = {
    CPARSER_NODE_STRING,
    0,
    "<STRING:name>",
    NULL,
    NULL,
    &cparser_node_monther_tamper_name_root_connect_protocol_protocol_object_var_port_number_username_name_password
};

cparser_node_t cparser_node_monther_tamper_name_root_connect_protocol_protocol_object_var_port_number_username = {
    CPARSER_NODE_KEYWORD,
    0,
    "username",
    NULL,
    NULL,
    &cparser_node_monther_tamper_name_root_connect_protocol_protocol_object_var_port_number_username_name
};

cparser_node_t cparser_node_monther_tamper_name_root_connect_protocol_protocol_object_var_port_number = {
    CPARSER_NODE_UINT,
    0,
    "<UINT:number>",
    NULL,
    NULL,
    &cparser_node_monther_tamper_name_root_connect_protocol_protocol_object_var_port_number_username
};

cparser_node_t cparser_node_monther_tamper_name_root_connect_protocol_protocol_object_var_port = {
    CPARSER_NODE_KEYWORD,
    0,
    "port",
    NULL,
    NULL,
    &cparser_node_monther_tamper_name_root_connect_protocol_protocol_object_var_port_number
};

cparser_node_t cparser_node_monther_tamper_name_root_connect_protocol_protocol_object_var = {
    CPARSER_NODE_STRING,
    0,
    "<STRING:var>",
    NULL,
    NULL,
    &cparser_node_monther_tamper_name_root_connect_protocol_protocol_object_var_port
};

cparser_list_node_t cparser_list_node_monther_tamper_name_root_connect_protocol_protocol_object_hostname = {
    NULL,
    "hostname"
 };

cparser_list_node_t cparser_list_node_monther_tamper_name_root_connect_protocol_protocol_object_server_ip = {
    &cparser_list_node_monther_tamper_name_root_connect_protocol_protocol_object_hostname,
    "server-ip"
 };

cparser_node_t cparser_node_monther_tamper_name_root_connect_protocol_protocol_object = {
    CPARSER_NODE_LIST,
    0,
    &cparser_list_node_monther_tamper_name_root_connect_protocol_protocol_object_server_ip,
    NULL,
    NULL,
    &cparser_node_monther_tamper_name_root_connect_protocol_protocol_object_var
};

cparser_list_node_t cparser_list_node_monther_tamper_name_root_connect_protocol_protocol_ftp = {
    NULL,
    "ftp"
 };

cparser_list_node_t cparser_list_node_monther_tamper_name_root_connect_protocol_protocol_sftp = {
    &cparser_list_node_monther_tamper_name_root_connect_protocol_protocol_ftp,
    "sftp"
 };

cparser_node_t cparser_node_monther_tamper_name_root_connect_protocol_protocol = {
    CPARSER_NODE_LIST,
    0,
    &cparser_list_node_monther_tamper_name_root_connect_protocol_protocol_sftp,
    NULL,
    NULL,
    &cparser_node_monther_tamper_name_root_connect_protocol_protocol_object
};

cparser_node_t cparser_node_monther_tamper_name_root_connect_protocol = {
    CPARSER_NODE_KEYWORD,
    0,
    "protocol",
    NULL,
    NULL,
    &cparser_node_monther_tamper_name_root_connect_protocol_protocol
};

cparser_node_t cparser_node_monther_tamper_name_root_connect = {
    CPARSER_NODE_KEYWORD,
    0,
    "connect",
    NULL,
    &cparser_node_monther_tamper_name_root_document_root,
    &cparser_node_monther_tamper_name_root_connect_protocol
};

cparser_node_t cparser_node_monther_tamper_name_root_email_address_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_son_email_address,
    "config email address",
    NULL,
    NULL
};

cparser_node_t cparser_node_monther_tamper_name_root_email_address = {
    CPARSER_NODE_STRING,
    0,
    "<STRING:address>",
    NULL,
    NULL,
    &cparser_node_monther_tamper_name_root_email_address_eol
};

cparser_node_t cparser_node_monther_tamper_name_root_email = {
    CPARSER_NODE_KEYWORD,
    0,
    "email",
    NULL,
    &cparser_node_monther_tamper_name_root_connect,
    &cparser_node_monther_tamper_name_root_email_address
};

cparser_node_t cparser_node_monther_tamper_name_root_no_disk_size_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_son_no_disk_size,
    "restore the defualt size (50M)",
    NULL,
    NULL
};

cparser_node_t cparser_node_monther_tamper_name_root_no_disk_size = {
    CPARSER_NODE_KEYWORD,
    0,
    "disk-size",
    NULL,
    NULL,
    &cparser_node_monther_tamper_name_root_no_disk_size_eol
};

cparser_node_t cparser_node_monther_tamper_name_root_no_monitor_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_son_no_monitor,
    "disable monitor",
    NULL,
    NULL
};

cparser_node_t cparser_node_monther_tamper_name_root_no_monitor = {
    CPARSER_NODE_KEYWORD,
    0,
    "monitor",
    NULL,
    &cparser_node_monther_tamper_name_root_no_disk_size,
    &cparser_node_monther_tamper_name_root_no_monitor_eol
};

cparser_node_t cparser_node_monther_tamper_name_root_no_restore_mode_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_son_no_restore_mode,
    "default auto restore",
    NULL,
    NULL
};

cparser_node_t cparser_node_monther_tamper_name_root_no_restore_mode = {
    CPARSER_NODE_KEYWORD,
    0,
    "restore-mode",
    NULL,
    &cparser_node_monther_tamper_name_root_no_monitor,
    &cparser_node_monther_tamper_name_root_no_restore_mode_eol
};

cparser_node_t cparser_node_monther_tamper_name_root_no_monitor_file_type_exclude_extension_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_son_no_monitor_file_type_exclude_extension,
    "no monitor file type",
    NULL,
    NULL
};

cparser_node_t cparser_node_monther_tamper_name_root_no_monitor_file_type_exclude_extension = {
    CPARSER_NODE_STRING,
    0,
    "<STRING:extension>",
    NULL,
    NULL,
    &cparser_node_monther_tamper_name_root_no_monitor_file_type_exclude_extension_eol
};

cparser_node_t cparser_node_monther_tamper_name_root_no_monitor_file_type_exclude = {
    CPARSER_NODE_KEYWORD,
    0,
    "exclude",
    NULL,
    NULL,
    &cparser_node_monther_tamper_name_root_no_monitor_file_type_exclude_extension
};

cparser_node_t cparser_node_monther_tamper_name_root_no_monitor_file_type = {
    CPARSER_NODE_KEYWORD,
    0,
    "monitor-file-type",
    NULL,
    &cparser_node_monther_tamper_name_root_no_restore_mode,
    &cparser_node_monther_tamper_name_root_no_monitor_file_type_exclude
};

cparser_node_t cparser_node_monther_tamper_name_root_no_monitor_file_size_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_son_no_monitor_file_size,
    "no config monitor file size",
    NULL,
    NULL
};

cparser_node_t cparser_node_monther_tamper_name_root_no_monitor_file_size = {
    CPARSER_NODE_KEYWORD,
    0,
    "monitor-file-size",
    NULL,
    &cparser_node_monther_tamper_name_root_no_monitor_file_type,
    &cparser_node_monther_tamper_name_root_no_monitor_file_size_eol
};

cparser_node_t cparser_node_monther_tamper_name_root_no_monitor_folder_other_folder_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_son_no_monitor_folder_other_folder,
    "no monitor folder with other-folder",
    NULL,
    NULL
};

cparser_node_t cparser_node_monther_tamper_name_root_no_monitor_folder_other_folder = {
    CPARSER_NODE_KEYWORD,
    0,
    "other-folder",
    NULL,
    NULL,
    &cparser_node_monther_tamper_name_root_no_monitor_folder_other_folder_eol
};

cparser_node_t cparser_node_monther_tamper_name_root_no_monitor_folder_root_folder_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_son_no_monitor_folder_root_folder,
    "no monitor folder with root-folder",
    NULL,
    NULL
};

cparser_node_t cparser_node_monther_tamper_name_root_no_monitor_folder_root_folder = {
    CPARSER_NODE_KEYWORD,
    0,
    "root-folder",
    NULL,
    &cparser_node_monther_tamper_name_root_no_monitor_folder_other_folder,
    &cparser_node_monther_tamper_name_root_no_monitor_folder_root_folder_eol
};

cparser_node_t cparser_node_monther_tamper_name_root_no_monitor_folder_depth_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_son_no_monitor_folder_depth,
    "no monitor folder with depth",
    NULL,
    NULL
};

cparser_node_t cparser_node_monther_tamper_name_root_no_monitor_folder_depth = {
    CPARSER_NODE_KEYWORD,
    0,
    "depth",
    NULL,
    &cparser_node_monther_tamper_name_root_no_monitor_folder_root_folder,
    &cparser_node_monther_tamper_name_root_no_monitor_folder_depth_eol
};

cparser_node_t cparser_node_monther_tamper_name_root_no_monitor_folder = {
    CPARSER_NODE_KEYWORD,
    0,
    "monitor-folder",
    NULL,
    &cparser_node_monther_tamper_name_root_no_monitor_file_size,
    &cparser_node_monther_tamper_name_root_no_monitor_folder_depth
};

cparser_node_t cparser_node_monther_tamper_name_root_no_document_root_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_son_no_document_root,
    "no  the document root",
    NULL,
    NULL
};

cparser_node_t cparser_node_monther_tamper_name_root_no_document_root = {
    CPARSER_NODE_KEYWORD,
    0,
    "document-root",
    NULL,
    &cparser_node_monther_tamper_name_root_no_monitor_folder,
    &cparser_node_monther_tamper_name_root_no_document_root_eol
};

cparser_node_t cparser_node_monther_tamper_name_root_no_connect_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_son_no_connect,
    "delete connection attribution with server-ip",
    NULL,
    NULL
};

cparser_node_t cparser_node_monther_tamper_name_root_no_connect = {
    CPARSER_NODE_KEYWORD,
    0,
    "connect",
    NULL,
    &cparser_node_monther_tamper_name_root_no_document_root,
    &cparser_node_monther_tamper_name_root_no_connect_eol
};

cparser_node_t cparser_node_monther_tamper_name_root_no_email_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_son_no_email,
    "delete email address",
    NULL,
    NULL
};

cparser_node_t cparser_node_monther_tamper_name_root_no_email = {
    CPARSER_NODE_KEYWORD,
    0,
    "email",
    NULL,
    &cparser_node_monther_tamper_name_root_no_connect,
    &cparser_node_monther_tamper_name_root_no_email_eol
};

cparser_node_t cparser_node_monther_tamper_name_root_no_description_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_son_no_description,
    "delete the description",
    NULL,
    NULL
};

cparser_node_t cparser_node_monther_tamper_name_root_no_description = {
    CPARSER_NODE_KEYWORD,
    0,
    "description",
    NULL,
    &cparser_node_monther_tamper_name_root_no_email,
    &cparser_node_monther_tamper_name_root_no_description_eol
};

cparser_node_t cparser_node_monther_tamper_name_root_no = {
    CPARSER_NODE_KEYWORD,
    0,
    "no",
    NULL,
    &cparser_node_monther_tamper_name_root_email,
    &cparser_node_monther_tamper_name_root_no_description
};

cparser_node_t cparser_node_monther_tamper_name_root_description_content_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_son_description_content,
    "config the tamper description",
    NULL,
    NULL
};

cparser_node_t cparser_node_monther_tamper_name_root_description_content = {
    CPARSER_NODE_STRING,
    0,
    "<STRING:content>",
    NULL,
    NULL,
    &cparser_node_monther_tamper_name_root_description_content_eol
};

cparser_node_t cparser_node_monther_tamper_name_root_description = {
    CPARSER_NODE_KEYWORD,
    0,
    "description",
    NULL,
    &cparser_node_monther_tamper_name_root_no,
    &cparser_node_monther_tamper_name_root_description_content
};

cparser_node_t cparser_node_monther_tamper_name_root = {
    CPARSER_NODE_ROOT,
    0,
    NULL,
    "Root of submode son",
    NULL,
    &cparser_node_monther_tamper_name_root_description
};

cparser_node_t cparser_node_st_configure_root_tamper_name_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_monther_tamper_name,
    "Enter tamper mode",
    NULL,
    &cparser_node_monther_tamper_name_root
};

cparser_node_t cparser_node_st_configure_root_tamper_name = {
    CPARSER_NODE_STRING,
    0,
    "<STRING:name>",
    NULL,
    NULL,
    &cparser_node_st_configure_root_tamper_name_eol
};

cparser_node_t cparser_node_st_configure_root_tamper = {
    CPARSER_NODE_KEYWORD,
    0,
    "tamper",
    NULL,
    NULL,
    &cparser_node_st_configure_root_tamper_name
};

cparser_node_t cparser_node_st_configure_root_no_tamper_name_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_monther_no_tamper_name,
    "delete a tamper",
    NULL,
    NULL
};

cparser_node_t cparser_node_st_configure_root_no_tamper_name = {
    CPARSER_NODE_STRING,
    0,
    "<STRING:name>",
    NULL,
    NULL,
    &cparser_node_st_configure_root_no_tamper_name_eol
};

cparser_node_t cparser_node_st_configure_root_no_tamper = {
    CPARSER_NODE_KEYWORD,
    0,
    "tamper",
    NULL,
    NULL,
    &cparser_node_st_configure_root_no_tamper_name
};

cparser_node_t cparser_node_st_configure_root_no = {
    CPARSER_NODE_KEYWORD,
    0,
    "no",
    NULL,
    &cparser_node_st_configure_root_tamper,
    &cparser_node_st_configure_root_no_tamper
};

cparser_node_t cparser_node_st_configure_root = {
    CPARSER_NODE_ROOT,
    0,
    NULL,
    "Root of submode monther",
    NULL,
    &cparser_node_st_configure_root_no
};

cparser_node_t cparser_node_enable_root_configure_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_st_configure,
    "enter tamper submode",
    NULL,
    &cparser_node_st_configure_root
};

cparser_node_t cparser_node_enable_root_configure = {
    CPARSER_NODE_KEYWORD,
    0,
    "configure",
    NULL,
    NULL,
    &cparser_node_enable_root_configure_eol
};

cparser_node_t cparser_node_enable_root_load_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_st_load,
    "load config",
    NULL,
    NULL
};

cparser_node_t cparser_node_enable_root_load = {
    CPARSER_NODE_KEYWORD,
    0,
    "load",
    NULL,
    &cparser_node_enable_root_configure,
    &cparser_node_enable_root_load_eol
};

cparser_node_t cparser_node_enable_root_write_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_st_write,
    "save config",
    NULL,
    NULL
};

cparser_node_t cparser_node_enable_root_write = {
    CPARSER_NODE_KEYWORD,
    0,
    "write",
    NULL,
    &cparser_node_enable_root_load,
    &cparser_node_enable_root_write_eol
};

cparser_node_t cparser_node_enable_root = {
    CPARSER_NODE_ROOT,
    0,
    NULL,
    "Root of submode st",
    NULL,
    &cparser_node_enable_root_write
};

cparser_node_t cparser_node_enable_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_enable,
    "enter config submode",
    NULL,
    &cparser_node_enable_root
};

cparser_node_t cparser_node_enable = {
    CPARSER_NODE_KEYWORD,
    0,
    "enable",
    NULL,
    NULL,
    &cparser_node_enable_eol
};

cparser_node_t cparser_root = {
    CPARSER_NODE_ROOT,
    0,
    NULL,
    "Root node of the parser tree",
    NULL,
    &cparser_node_enable
};

